project:
  type: website

website:
  favicon: assets/favicon.svg
  search: false
  navbar:
    logo: assets/logo.svg
    logo-alt: University of Bristol
    pinned: true
  sidebar:
    contents:
      - text: About our group
        href: index.qmd
      - text: Join our group
        href: join.qmd
      - text: Training courses
        href: https://bristol-training.github.io
      - contact.qmd
    pinned: true
  page-footer:
    center: Supported by the [Jean Golding Institute](https://www.bristol.ac.uk/golding/) Â© [CC-BY 4.0](http://creativecommons.org/licenses/by/4.0/)

format:
  html:
    theme: assets/styles.scss
    page-layout: full
